## 10 Apr Naive Bayes - 2

Q1. A company conducted a survey of its employees and found that 70% of the employees use the 
company's health insurance plan, while 40% of the employees who use the plan are smokers. What is the 
probability that an employee is a smoker given that he/she uses the health insurance plan?


Ans: 19.5%

Q2. What is the difference between Bernoulli Naive Bayes and Multinomial Naive Bayes?

Ans:
    
    The main difference between Bernoulli Naive Bayes and Multinomial Naive Bayes is in how they model the features. In Bernoulli Naive Bayes, each feature is a binary variable that indicates whether a particular word or token is present or absent in the document. For example, in a spam classification problem, each feature might correspond to a particular word that is commonly found in spam emails, and the value of the feature would be 1 if the word is present in the email and 0 otherwise.

    In contrast, in Multinomial Naive Bayes, each feature is a count variable that indicates how many times a particular word or token appears in the document. For example, in a sentiment classification problem, each feature might correspond to a particular word that is associated with a positive or negative sentiment, and the value of the feature would be the number of times the word appears in the document.

Q3. How does Bernoulli Naive Bayes handle missing values?

Ans:


    In Bernoulli Naive Bayes, missing values are typically handled by treating them as a separate category. Specifically, for each feature with missing values, a new category is added to the feature set to represent the missing values. This category is usually labeled as "missing" or "unknown".


Q4. Can Gaussian Naive Bayes be used for multi-class classification?

ans:

Yes

Q5. Assignment

Data preparation:

Download the "Spambase Data Set" from the UCI Machine Learning Repository (https://archive.ics.uci.edu/ml/
datasets/Spambase). This dataset contains email messages, where the goal is to predict whether a message 
is spam or not based on several input features.

In [1]:
## Load Dataset

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Spambase Data Set.csv")
df.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_%3B  char_freq_%28  \
0             0.00            0.00  ...           0.00          0.000   
1             0.00            0.94  ...           0.00          0.132   
2             0.64            0.25  ...           0.01          0.143   
3             0.31            0.63  ...           0.00          0.137   
4             0.31            0.63  ...           0.00          0.135   

   char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
0            0.0          0.778          0.000          0.000   
1            0.0          0.372          0.180          0.048   
2            0.0          0.276          0.184          0.010   
3            0.0          0.137          0.000          0.000   
4            0.0          0.135          0.000          0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  class  
0                       278      1  
1                      1028      1  
2                      2259      1  
3                       191      1  
4                       191      1  

[5 rows x 58 columns]

In [4]:
## Check the missing value

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 

In [5]:
df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_fre

## CONCLUSION : 
No Missing Values

In [6]:
## Check the outliers

import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df.columns

Index(['word_freq_make', 'word_freq_address', 'word_freq_all', 'word_freq_3d',
       'word_freq_our', 'word_freq_over', 'word_freq_remove',
       'word_freq_internet', 'word_freq_order', 'word_freq_mail',
       'word_freq_receive', 'word_freq_will', 'word_freq_people',
       'word_freq_report', 'word_freq_addresses', 'word_freq_free',
       'word_freq_business', 'word_freq_email', 'word_freq_you',
       'word_freq_credit', 'word_freq_your', 'word_freq_font', 'word_freq_000',
       'word_freq_money', 'word_freq_hp', 'word_freq_hpl', 'word_freq_george',
       'word_freq_650', 'word_freq_lab', 'word_freq_labs', 'word_freq_telnet',
       'word_freq_857', 'word_freq_data', 'word_freq_415', 'word_freq_85',
       'word_freq_technology', 'word_freq_1999', 'word_freq_parts',
       'word_freq_pm', 'word_freq_direct', 'word_freq_cs', 'word_freq_meeting',
       'word_freq_original', 'word_freq_project', 'word_freq_re',
       'word_freq_edu', 'word_freq_table', 'word_freq_conference',


In [8]:
# Dependent and Independent Feature

X = df[['word_freq_make', 'word_freq_address', 'word_freq_all', 'word_freq_3d',
       'word_freq_our', 'word_freq_over', 'word_freq_remove',
       'word_freq_internet', 'word_freq_order', 'word_freq_mail',
       'word_freq_receive', 'word_freq_will', 'word_freq_people',
       'word_freq_report', 'word_freq_addresses', 'word_freq_free',
       'word_freq_business', 'word_freq_email', 'word_freq_you',
       'word_freq_credit', 'word_freq_your', 'word_freq_font', 'word_freq_000',
       'word_freq_money', 'word_freq_hp', 'word_freq_hpl', 'word_freq_george',
       'word_freq_650', 'word_freq_lab', 'word_freq_labs', 'word_freq_telnet',
       'word_freq_857', 'word_freq_data', 'word_freq_415', 'word_freq_85',
       'word_freq_technology', 'word_freq_1999', 'word_freq_parts',
       'word_freq_pm', 'word_freq_direct', 'word_freq_cs', 'word_freq_meeting',
       'word_freq_original', 'word_freq_project', 'word_freq_re',
       'word_freq_edu', 'word_freq_table', 'word_freq_conference',
       'char_freq_%3B', 'char_freq_%28', 'char_freq_%5B', 'char_freq_%21',
       'char_freq_%24', 'char_freq_%23', 'capital_run_length_average',
       'capital_run_length_longest', 'capital_run_length_total']]

In [9]:
y = df['class']

In [10]:
X.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_%3B  \
0             0.00            0.00  ...                   0.0           0.00   
1             0.00            0.94  ...                   0.0           0.00   
2             0.64            0.25  ...                   0.0           0.01   
3             0.31            0.63  ...                   0.0           0.00   
4             0.31            0.63  ...                   0.0           0.00   

   char_freq_%28  char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
0          0.000            0.0          0.778          0.000          0.000   
1          0.132            0.0          0.372          0.180          0.048   
2          0.143            0.0          0.276          0.184          0.010   
3          0.137            0.0          0.137          0.000          0.000   
4          0.135            0.0          0.135          0.000          0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  
0                       278  
1                      1028  
2                      2259  
3                       191  
4                       191  

[5 rows x 57 columns]

In [11]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [12]:
## Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=200)

#### Implementation:

Implement Bernoulli Naive Bayes, Multinomial Naive Bayes, and Gaussian Naive Bayes classifiers using the 
scikit-learn library in Python. Use 10-fold cross-validation to evaluate the performance of each classifier on the 
dataset. You should use the default hyperparameters for each classifier.

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

## Go with GaussianNB

In [14]:

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [15]:
y_pred = gnb.predict(X_test)

#### Results:

Report the following performance metrics for each classifier:
Accuracy, Precision, Recall, F1 score

In [16]:
accuracy_score(y_pred, y_test)

0.805

In [17]:
precision_score(y_pred, y_test)

0.9010989010989011

In [18]:
recall_score(y_pred, y_test)

0.7321428571428571

In [19]:
f1_score(y_pred, y_test)

0.8078817733990148

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.72      0.90      0.80        88
           1       0.90      0.73      0.81       112

    accuracy                           0.81       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.82      0.81      0.81       200



In [22]:
confusion_matrix(y_pred, y_test)

array([[79,  9],
       [30, 82]])

## Conclusion

79 : model predics +ve and Actually +ve 

9 : model predicts +ve and Actually -ve

30 : model predicts -ve and Actually +ve - Blunder Case

82 : model predicts -ve and Actually +ve 

## MultinomialNB

In [23]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)

In [24]:
confusion_matrix(y_pred2, y_test)

array([[92, 32],
       [17, 59]])

In [25]:
accuracy_score(y_pred2, y_test)

0.755

## Conclusion

92 : model predics +ve and Actually +ve 

32 : model predicts +ve and Actually -ve

17 : model predicts -ve and Actually +ve - Blunder Case

59 : model predicts -ve and Actually +ve 

In [26]:
## Bernouli Naive Bayes

In [27]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train, y_train)
y_pred3 = mnb.predict(X_test)

In [28]:
confusion_matrix(y_pred3, y_test)

array([[92, 32],
       [17, 59]])

In [29]:
accuracy_score(y_pred3, y_test)

0.755

## Discussion:

Discuss the results you obtained. Which variant of Naive Bayes performed the best? Why do you think that is 
the case? Are there any limitations of Naive Bayes that you observed

I will choose Multinomial Naive bias, as it gives less no of False Negative case